  /* 00 /wr */ NO_LOOKUP(X8664_DEC_ADD_EB_GB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 01 /wr */ NO_LOOKUP(X8664_DEC_ADD_EV_GV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 02 /wr */ NO_LOOKUP(X8664_DEC_ADD_GB_EB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 03 /wr */ NO_LOOKUP(X8664_DEC_ADD_GV_EV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 04 /wr */ NO_LOOKUP(X8664_DEC_ADD_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 05 /wr */ NO_LOOKUP(X8664_DEC_ADD_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 06 /wr */ INVALID
  /* 07 /wr */ INVALID
  /* 08 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EB_GB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 09 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EV_GV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 0A /wr */ NO_LOOKUP_(X8664_DEC_ADD_GB_EB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 0B /wr */ NO_LOOKUP_(X8664_DEC_ADD_GV_EV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 0C /wr */ NO_LOOKUP_(X8664_DEC_ADD_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 0D /wr */ NO_LOOKUP_(X8664_DEC_ADD_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))  
  /* 0E /wr */ INVALID
  /* 0F /wr */ INVALID
  /* 10 /wr */ NO_LOOKUP(X8664_DEC_ADC_EB_GB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 11 /wr */ NO_LOOKUP(X8664_DEC_ADC_EV_GV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 12 /wr */ NO_LOOKUP(X8664_DEC_ADC_GB_EB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 13 /wr */ NO_LOOKUP(X8664_DEC_ADC_GV_EV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 14 /wr */ NO_LOOKUP(X8664_DEC_ADC_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 15 /wr */ NO_LOOKUP(X8664_DEC_ADC_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 16 /wr */ INVALID
  /* 17 /wr */ INVALID
  /* 18 /wr */ NO_LOOKUP_(X8664_DEC_ADC_EB_GB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 19 /wr */ NO_LOOKUP_(X8664_DEC_ADC_EV_GV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 1A /wr */ NO_LOOKUP_(X8664_DEC_ADC_GB_EB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 1B /wr */ NO_LOOKUP_(X8664_DEC_ADC_GV_EV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 1C /wr */ NO_LOOKUP_(X8664_DEC_ADC_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 1D /wr */ NO_LOOKUP_(X8664_DEC_ADC_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 1E /wr */ INVALID
  /* 1F /wr */ INVALID
  /* 20 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EB_GB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 21 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EV_GV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 22 /wr */ NO_LOOKUP_(X8664_DEC_ADD_GB_EB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 23 /wr */ NO_LOOKUP_(X8664_DEC_ADD_GV_EV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 24 /wr */ NO_LOOKUP_(X8664_DEC_ADD_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 25 /wr */ NO_LOOKUP_(X8664_DEC_ADD_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 26 /wr */ INVALID
  /* 27 /wr */ INVALID
  /* 28 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EB_GB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 29 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EV_GV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 2A /wr */ NO_LOOKUP_(X8664_DEC_ADD_GB_EB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 2B /wr */ NO_LOOKUP_(X8664_DEC_ADD_GV_EV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 2C /wr */ NO_LOOKUP_(X8664_DEC_ADD_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 2D /wr */ NO_LOOKUP_(X8664_DEC_ADD_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 2E /wr */ INVALID
  /* 2F /wr */ INVALID
  /* 30 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EB_GB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 31 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EV_GV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 32 /wr */ NO_LOOKUP_(X8664_DEC_ADD_GB_EB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 33 /wr */ NO_LOOKUP_(X8664_DEC_ADD_GV_EV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 34 /wr */ NO_LOOKUP_(X8664_DEC_ADD_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 35 /wr */ NO_LOOKUP_(X8664_DEC_ADD_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 36 /wr */ INVALID
  /* 37 /wr */ INVALID
  /* 38 /wr */ NO_LOOKUP(X8664_DEC_CMP_EB_GB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 39 /wr */ NO_LOOKUP(X8664_DEC_CMP_EV_GV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 3A /wr */ NO_LOOKUP(X8664_DEC_CMP_GB_EB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 3B /wr */ NO_LOOKUP(X8664_DEC_CMP_GV_EV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 3C /wr */ NO_LOOKUP(X8664_DEC_CMP_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 3D /wr */ NO_LOOKUP(X8664_DEC_CMP_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 3E /wr */ INVALID
  /* 3F /wr */ INVALID
  /* 40 /wr */ INVALID // REX:
  /* 41 /wr */ INVALID // REX:
  /* 42 /wr */ INVALID // REX:
  /* 43 /wr */ INVALID // REX:
  /* 44 /wr */ INVALID // REX:
  /* 45 /wr */ INVALID // REX:
  /* 46 /wr */ INVALID // REX:
  /* 47 /wr */ INVALID // REX:
  /* 48 /wr */ INVALID // REX:
  /* 49 /wr */ INVALID // REX:
  /* 4A /wr */ INVALID // REX:
  /* 4B /wr */ INVALID // REX:
  /* 4C /wr */ INVALID // REX:
  /* 4D /wr */ INVALID // REX:
  /* 4E /wr */ INVALID // REX:
  /* 4F /wr */ INVALID // REX:
  /* 50 /wr */ NO_LOOKUP(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 51 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 52 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 53 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 54 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 55 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 56 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 57 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 58 /wr */ NO_LOOKUP(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 59 /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5A /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5B /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5C /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5D /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5E /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5F /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 60 /wr */ INVALID
  /* 61 /wr */ INVALID
  /* 62 /wr */ INVALID
  /* 63 /wr */ NO_LOOKUP_(invalid, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* 64 /wr */ INVALID
  /* 65 /wr */ INVALID
  /* 66 /wr */ INVALID
  /* 67 /wr */ INVALID
  /* 68 /wr */ NO_LOOKUP_(invalid, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 69 /wr */ NO_LOOKUP_(invalid, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_MUL))
  /* 6A /wr */ NO_LOOKUP_(invalid, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 6B /wr */ NO_LOOKUP_(invalid, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_MUL))
  /* 6C /wr */ INVALID // string
  /* 6D /wr */ INVALID // string
  /* 6E /wr */ INVALID // string
  /* 6F /wr */ INVALID // string
  /* 70 /wr */ NO_LOOKUP(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 71 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 72 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 73 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 74 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 75 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 76 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 77 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 78 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 79 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7A /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7B /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7C /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7D /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7E /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7F /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 80 /wr */ NO_LOOKUP(X8664_GROUP_1_8BITS_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 81 /wr */ NO_LOOKUP(X8664_GROUP_1_ZBITS_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 82 /wr */ INVALID
  /* 83 /wr */ NO_LOOKUP_(X8664_GROUP_1_ZBITS_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 84 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EB_GB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 85 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EV_GV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 86 /wr */ INVALID
  /* 87 /wr */ INVALID
  /* 88 /wr */ NO_LOOKUP(X8664_MOV_EB_GB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* 89 /wr */ NO_LOOKUP(X8664_MOV_EV_GV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* 8A /wr */ NO_LOOKUP(X8664_MOV_GB_EB_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* 8B /wr */ NO_LOOKUP(X8664_MOV_GV_EV_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* 8C /wr */ INVALID
  /* 8D /wr */ INVALID      // LEA
  /* 8E /wr */ INVALID
  /* 8F /wr */ INVALID
  /* 90 /wr */ INVALID  // handles XCHG R8w, AX
  /* 91 /wr */ INVALID
  /* 92 /wr */ INVALID
  /* 93 /wr */ INVALID
  /* 94 /wr */ INVALID
  /* 95 /wr */ INVALID
  /* 96 /wr */ INVALID
  /* 97 /wr */ INVALID
  /* 98 /wr */ INVALID
  /* 99 /wr */ INVALID
  /* 9A /wr */ INVALID
  /* 9B /wr */ INVALID
  /* 9C /wr */ INVALID
  /* 9D /wr */ INVALID
  /* 9E /wr */ INVALID
  /* 9F /wr */ INVALID
  /* A0 /wr */ INVALID
  /* A1 /wr */ INVALID
  /* A2 /wr */ INVALID
  /* A3 /wr */ INVALID
  /* A4 /wr */ INVALID
  /* A5 /wr */ INVALID
  /* A6 /wr */ INVALID
  /* A7 /wr */ INVALID
  /* A8 /wr */ INVALID
  /* A9 /wr */ INVALID
  /* AA /wr */ INVALID
  /* AB /wr */ INVALID
  /* AC /wr */ INVALID
  /* AD /wr */ INVALID
  /* AE /wr */ INVALID
  /* AF /wr */ INVALID
  /* B0 /wr */ NO_LOOKUP(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B1 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B2 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B3 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B4 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B5 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B6 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B7 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B8 /wr */ NO_LOOKUP(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B9 /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BA /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BB /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BC /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BD /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BE /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BF /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* C0 /wr */ NO_LOOKUP_(X8664_GROUP_1_8BITS_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* C1 /wr */ NO_LOOKUP_(X8664_GROUP_1_ZBITS_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* C2 /wr */ NO_LOOKUP_(invalid, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* C3 /wr */ NO_LOOKUP_(invalid, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* C4 /wr */ INVALID
  /* C5 /wr */ INVALID
  /* C6 /wr */ INVALID
  /* C7 /wr */ INVALID
  /* C8 /wr */ INVALID
  /* C9 /wr */ INVALID
  /* CA /wr */ INVALID
  /* CB /wr */ INVALID
  /* CC /wr */ INVALID
  /* CD /wr */ INVALID
  /* CE /wr */ INVALID
  /* CF /wr */ INVALID
  /* D0 /wr */ NO_LOOKUP_(X8664_GROUP_1_8BITS_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* D1 /wr */ NO_LOOKUP_(X8664_GROUP_1_ZBITS_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* D2 /wr */ NO_LOOKUP(X8664_GROUP_2_CL_8BITS_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* D3 /wr */ NO_LOOKUP(X8664_GROUP_2_CL_ZBITS_REG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* D4 /wr */ INVALID
  /* D5 /wr */ INVALID
  /* D6 /wr */ INVALID
  /* D7 /wr */ INVALID
  /* D8 /wr */ INVALID
  /* D9 /wr */ INVALID
  /* DA /wr */ INVALID
  /* DB /wr */ INVALID
  /* DC /wr */ INVALID
  /* DD /wr */ INVALID
  /* DE /wr */ INVALID
  /* DF /wr */ INVALID
  /* E0 /wr */ INVALID
  /* E1 /wr */ INVALID
  /* E2 /wr */ INVALID
  /* E3 /wr */ INVALID
  /* E4 /wr */ INVALID
  /* E5 /wr */ INVALID
  /* E6 /wr */ INVALID
  /* E7 /wr */ INVALID
  /* E8 /wr */ NO_LOOKUP(X8664_CALL, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* E9 /wr */ NO_LOOKUP(X8664_JUMP_UNCOND, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* EA /wr */ INVALID
  /* EB /wr */ NO_LOOKUP_(X8664_JUMP_UNCOND, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* EC /wr */ INVALID
  /* ED /wr */ INVALID
  /* EE /wr */ INVALID
  /* EF /wr */ INVALID
  /* F0 /wr */ INVALID // LOCK
  /* F1 /wr */ INVALID
  /* F2 /wr */ INVALID // REPNE/REPNZ
  /* F3 /wr */ INVALID // REP, REPE/REPZ
  /* F4 /wr */ INVALID
  /* F5 /wr */ INVALID
  /* F6 /wr */ INVALID
  /* F7 /wr */ INVALID
  /* F8 /wr */ INVALID
  /* F9 /wr */ INVALID
  /* FA /wr */ INVALID
  /* FB /wr */ INVALID
  /* FC /wr */ INVALID
  /* FD /wr */ INVALID
  /* FE /wr */ INVALID
  /* FF /wr */ INVALID
  /* 0F 00 /wr */ INVALID
  /* 0F 01 /wr */ INVALID
  /* 0F 02 /wr */ INVALID
  /* 0F 03 /wr */ INVALID
  /* 0F 04 /wr */ INVALID
  /* 0F 05 /wr */ INVALID
  /* 0F 06 /wr */ INVALID
  /* 0F 07 /wr */ INVALID
  /* 0F 08 /wr */ INVALID
  /* 0F 09 /wr */ INVALID
  /* 0F 0A /wr */ INVALID
  /* 0F 0B /wr */ INVALID
  /* 0F 0C /wr */ INVALID
  /* 0F 0D /wr */ INVALID             // 3DNow! PREFETCH on AMD, NOP on Intel
  /* 0F 0E /wr */ INVALID           // 3DNow! FEMMS
#if BX_SUPPORT_3DNOW
  /* 0F 0F /wr */ INVALID
#else
  /* 0F 0F /wr */ INVALID
#endif
  /* 0F 10 /wr */ INVALID
  /* 0F 11 /wr */ INVALID
  /* 0F 12 /wr */ INVALID
  /* 0F 13 /wr */ INVALID  // MOVLPS/PD SSE group
  /* 0F 14 /wr */ INVALID
  /* 0F 15 /wr */ INVALID
  /* 0F 16 /wr */ INVALID
  /* 0F 17 /wr */ INVALID  // MOHLPS/PD SSE group
  /* 0F 18 /wr */ INVALID    // PREFETCH HINT
  /* 0F 19 /wr */ INVALID    // multi-byte NOP
  /* 0F 1A /wr */ INVALID    // multi-byte NOP
  /* 0F 1B /wr */ INVALID    // multi-byte NOP
  /* 0F 1C /wr */ INVALID    // multi-byte NOP
  /* 0F 1D /wr */ INVALID    // multi-byte NOP
  /* 0F 1E /wr */ INVALID    // multi-byte NOP
  /* 0F 1F /wr */ INVALID    // multi-byte NOP
  /* 0F 20 /wr */ INVALID
  /* 0F 21 /wr */ INVALID
  /* 0F 22 /wr */ INVALID
  /* 0F 23 /wr */ INVALID
  /* 0F 24 /wr */ INVALID
  /* 0F 25 /wr */ INVALID
  /* 0F 26 /wr */ INVALID
  /* 0F 27 /wr */ INVALID
  /* 0F 28 /wr */ INVALID
  /* 0F 29 /wr */ INVALID
  /* 0F 2A /wr */ INVALID
  /* 0F 2B /wr */ INVALID // MOVNTPS/PD/SS/SD
  /* 0F 2C /wr */ INVALID
  /* 0F 2D /wr */ INVALID
  /* 0F 2E /wr */ INVALID
  /* 0F 2F /wr */ INVALID
  /* 0F 30 /wr */ INVALID
  /* 0F 31 /wr */ INVALID
  /* 0F 32 /wr */ INVALID
  /* 0F 33 /wr */ INVALID
  /* 0F 34 /wr */ INVALID
  /* 0F 35 /wr */ INVALID
  /* 0F 36 /wr */ INVALID
  /* 0F 37 /wr */ INVALID
#if (BX_SUPPORT_SSE >= 4) || (BX_SUPPORT_SSE >= 3 && BX_SUPPORT_SSE_EXTENSION > 0)
  /* 0F 38 /wr */ INVALID // 3-byte escape
#else
  /* 0F 38 /wr */ INVALID
#endif
  /* 0F 39 /wr */ INVALID
#if (BX_SUPPORT_SSE >= 4) || (BX_SUPPORT_SSE >= 3 && BX_SUPPORT_SSE_EXTENSION > 0)
  /* 0F 3A /wr */ INVALID // 3-byte escape
#else
  /* 0F 3A /wr */ INVALID
#endif
  /* 0F 3B /wr */ INVALID
  /* 0F 3C /wr */ INVALID
  /* 0F 3D /wr */ INVALID
  /* 0F 3E /wr */ INVALID
  /* 0F 3F /wr */ INVALID
  /* 0F 40 /wr */ INVALID
  /* 0F 41 /wr */ INVALID
  /* 0F 42 /wr */ INVALID
  /* 0F 43 /wr */ INVALID
  /* 0F 44 /wr */ INVALID
  /* 0F 45 /wr */ INVALID
  /* 0F 46 /wr */ INVALID
  /* 0F 47 /wr */ INVALID
  /* 0F 48 /wr */ INVALID
  /* 0F 49 /wr */ INVALID
  /* 0F 4A /wr */ INVALID
  /* 0F 4B /wr */ INVALID
  /* 0F 4C /wr */ INVALID
  /* 0F 4D /wr */ INVALID
  /* 0F 4E /wr */ INVALID
  /* 0F 4F /wr */ INVALID
  /* 0F 50 /wr */ INVALID
  /* 0F 51 /wr */ INVALID
  /* 0F 52 /wr */ INVALID
  /* 0F 53 /wr */ INVALID
  /* 0F 54 /wr */ INVALID
  /* 0F 55 /wr */ INVALID
  /* 0F 56 /wr */ INVALID
  /* 0F 57 /wr */ INVALID
  /* 0F 58 /wr */ INVALID
  /* 0F 59 /wr */ INVALID
  /* 0F 5A /wr */ INVALID
  /* 0F 5B /wr */ INVALID
  /* 0F 5C /wr */ INVALID
  /* 0F 5D /wr */ INVALID
  /* 0F 5E /wr */ INVALID
  /* 0F 5F /wr */ INVALID
  /* 0F 60 /wr */ INVALID
  /* 0F 61 /wr */ INVALID
  /* 0F 62 /wr */ INVALID
  /* 0F 63 /wr */ INVALID
  /* 0F 64 /wr */ INVALID
  /* 0F 65 /wr */ INVALID
  /* 0F 66 /wr */ INVALID
  /* 0F 67 /wr */ INVALID
  /* 0F 68 /wr */ INVALID
  /* 0F 69 /wr */ INVALID
  /* 0F 6A /wr */ INVALID
  /* 0F 6B /wr */ INVALID
  /* 0F 6C /wr */ INVALID
  /* 0F 6D /wr */ INVALID
  /* 0F 6E /wr */ INVALID
  /* 0F 6F /wr */ INVALID
  /* 0F 70 /wr */ INVALID
  /* 0F 71 /wr */ INVALID
  /* 0F 72 /wr */ INVALID
  /* 0F 73 /wr */ INVALID
  /* 0F 74 /wr */ INVALID
  /* 0F 75 /wr */ INVALID
  /* 0F 76 /wr */ INVALID
  /* 0F 77 /wr */ INVALID
  /* 0F 78 /wr */ INVALID
  /* 0F 79 /wr */ INVALID
  /* 0F 7A /wr */ INVALID
  /* 0F 7B /wr */ INVALID
  /* 0F 7C /wr */ INVALID
  /* 0F 7D /wr */ INVALID
  /* 0F 7E /wr */ INVALID
  /* 0F 7F /wr */ INVALID
  /* 0F 80 /wr */ NO_LOOKUP(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 81 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 82 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 83 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 84 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 85 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 86 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 87 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 88 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 89 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8A /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8B /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8C /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8D /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8E /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8F /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 90 /wr */ INVALID
  /* 0F 91 /wr */ INVALID
  /* 0F 92 /wr */ INVALID
  /* 0F 93 /wr */ INVALID
  /* 0F 94 /wr */ INVALID
  /* 0F 95 /wr */ INVALID
  /* 0F 96 /wr */ INVALID
  /* 0F 97 /wr */ INVALID
  /* 0F 98 /wr */ INVALID
  /* 0F 99 /wr */ INVALID
  /* 0F 9A /wr */ INVALID
  /* 0F 9B /wr */ INVALID
  /* 0F 9C /wr */ INVALID
  /* 0F 9D /wr */ INVALID
  /* 0F 9E /wr */ INVALID
  /* 0F 9F /wr */ INVALID
  /* 0F A0 /wr */ INVALID
  /* 0F A1 /wr */ INVALID
  /* 0F A2 /wr */ INVALID
  /* 0F A3 /wr */ INVALID
  /* 0F A4 /wr */ INVALID
  /* 0F A5 /wr */ INVALID
  /* 0F A6 /wr */ INVALID
  /* 0F A7 /wr */ INVALID
  /* 0F A8 /wr */ INVALID
  /* 0F A9 /wr */ INVALID
  /* 0F AA /wr */ INVALID
  /* 0F AB /wr */ INVALID
  /* 0F AC /wr */ INVALID
  /* 0F AD /wr */ INVALID
  /* 0F AE /wr */ INVALID
  /* 0F AF /wr */ INVALID
  /* 0F B0 /wr */ INVALID
  /* 0F B1 /wr */ INVALID
  /* 0F B2 /wr */ INVALID // LSS
  /* 0F B3 /wr */ INVALID
  /* 0F B4 /wr */ INVALID // LFS
  /* 0F B5 /wr */ INVALID // LGS
  /* 0F B6 /wr */ INVALID
  /* 0F B7 /wr */ INVALID // MOVZX_GwEw
  /* 0F B8 /wr */ INVALID
  /* 0F B9 /wr */ INVALID
  /* 0F BA /wr */ INVALID
  /* 0F BB /wr */ INVALID
  /* 0F BC /wr */ INVALID
  /* 0F BD /wr */ INVALID
  /* 0F BE /wr */ INVALID
  /* 0F BF /wr */ INVALID // MOVSX_GwEw
  /* 0F C0 /wr */ INVALID
  /* 0F C1 /wr */ INVALID
  /* 0F C2 /wr */ INVALID
  /* 0F C3 /wr */ INVALID // MOVNTI SSE group
  /* 0F C4 /wr */ INVALID
  /* 0F C5 /wr */ INVALID
  /* 0F C6 /wr */ INVALID
  /* 0F C7 /wr */ INVALID // CMPXCHG8B G9 group
  /* 0F C8 /wr */ INVALID
  /* 0F C9 /wr */ INVALID
  /* 0F CA /wr */ INVALID
  /* 0F CB /wr */ INVALID
  /* 0F CC /wr */ INVALID
  /* 0F CD /wr */ INVALID
  /* 0F CE /wr */ INVALID
  /* 0F CF /wr */ INVALID
  /* 0F D0 /wr */ INVALID
  /* 0F D1 /wr */ INVALID
  /* 0F D2 /wr */ INVALID
  /* 0F D3 /wr */ INVALID
  /* 0F D4 /wr */ INVALID
  /* 0F D5 /wr */ INVALID
  /* 0F D6 /wr */ INVALID
  /* 0F D7 /wr */ INVALID
  /* 0F D8 /wr */ INVALID
  /* 0F D9 /wr */ INVALID
  /* 0F DA /wr */ INVALID
  /* 0F DB /wr */ INVALID
  /* 0F DC /wr */ INVALID
  /* 0F DD /wr */ INVALID
  /* 0F DE /wr */ INVALID
  /* 0F DF /wr */ INVALID
  /* 0F E0 /wr */ INVALID
  /* 0F E1 /wr */ INVALID
  /* 0F E2 /wr */ INVALID
  /* 0F E3 /wr */ INVALID
  /* 0F E4 /wr */ INVALID
  /* 0F E5 /wr */ INVALID
  /* 0F E6 /wr */ INVALID
  /* 0F E7 /wr */ INVALID // MOVNTQ/MOVNTDQ SSE group
  /* 0F E8 /wr */ INVALID
  /* 0F E9 /wr */ INVALID
  /* 0F EA /wr */ INVALID
  /* 0F EB /wr */ INVALID
  /* 0F EC /wr */ INVALID
  /* 0F ED /wr */ INVALID
  /* 0F EE /wr */ INVALID
  /* 0F EF /wr */ INVALID
  /* 0F F0 /wr */ INVALID // LDDQU SSE group
  /* 0F F1 /wr */ INVALID
  /* 0F F2 /wr */ INVALID
  /* 0F F3 /wr */ INVALID
  /* 0F F4 /wr */ INVALID
  /* 0F F5 /wr */ INVALID
  /* 0F F6 /wr */ INVALID
  /* 0F F7 /wr */ INVALID
  /* 0F F8 /wr */ INVALID
  /* 0F F9 /wr */ INVALID
  /* 0F FA /wr */ INVALID
  /* 0F FB /wr */ INVALID
  /* 0F FC /wr */ INVALID
  /* 0F FD /wr */ INVALID
  /* 0F FE /wr */ INVALID
  /* 0F FF /wr */ INVALID

/**********************************************************************************/

  // with memory

/**********************************************************************************/

  /* 00 /wr */ NO_LOOKUP(X8664_DEC_ADD_EB_GB_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 01 /wr */ NO_LOOKUP(X8664_DEC_ADD_EV_GV_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 02 /wr */ NO_LOOKUP(X8664_DEC_ADD_GB_EB_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 03 /wr */ NO_LOOKUP(X8664_DEC_ADD_GV_EV_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 04 /wr */ NO_LOOKUP_(X8664_DEC_ADD_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 05 /wr */ NO_LOOKUP_(X8664_DEC_ADD_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 06 /wr */ INVALID
  /* 07 /wr */ INVALID
  /* 08 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EB_GB_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* 09 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EV_GV_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* 0A /wr */ NO_LOOKUP_(X8664_DEC_ADD_GB_EB_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 0B /wr */ NO_LOOKUP_(X8664_DEC_ADD_GV_EV_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 0C /wr */ NO_LOOKUP_(X8664_DEC_ADD_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 0D /wr */ NO_LOOKUP_(X8664_DEC_ADD_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 0E /wr */ INVALID
  /* 0F /wr */ INVALID
  /* 10 /wr */ NO_LOOKUP(X8664_DEC_ADC_EB_GB_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 11 /wr */ NO_LOOKUP(X8664_DEC_ADC_EV_GV_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 12 /wr */ NO_LOOKUP(X8664_DEC_ADC_GB_EB_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 13 /wr */ NO_LOOKUP(X8664_DEC_ADC_GV_EV_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 14 /wr */ NO_LOOKUP_(X8664_DEC_ADC_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 15 /wr */ NO_LOOKUP_(X8664_DEC_ADC_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 16 /wr */ INVALID
  /* 17 /wr */ INVALID
  /* 18 /wr */ NO_LOOKUP_(X8664_DEC_ADC_EB_GB_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 19 /wr */ NO_LOOKUP_(X8664_DEC_ADC_EV_GV_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 1A /wr */ NO_LOOKUP_(X8664_DEC_ADC_GB_EB_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 1B /wr */ NO_LOOKUP_(X8664_DEC_ADC_GV_EV_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 1C /wr */ NO_LOOKUP_(X8664_DEC_ADC_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 1D /wr */ NO_LOOKUP_(X8664_DEC_ADC_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 1E /wr */ INVALID
  /* 1F /wr */ INVALID
  /* 20 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EB_GB_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* 21 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EV_GV_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* 22 /wr */ NO_LOOKUP_(X8664_DEC_ADD_GB_EB_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 23 /wr */ NO_LOOKUP_(X8664_DEC_ADD_GV_EV_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 24 /wr */ NO_LOOKUP_(X8664_DEC_ADD_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 25 /wr */ NO_LOOKUP_(X8664_DEC_ADD_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 26 /wr */ INVALID
  /* 27 /wr */ INVALID
  /* 28 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EB_GB_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 29 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EV_GV_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 2A /wr */ NO_LOOKUP_(X8664_DEC_ADD_GB_EB_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 2B /wr */ NO_LOOKUP_(X8664_DEC_ADD_GV_EV_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 2C /wr */ NO_LOOKUP_(X8664_DEC_ADD_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 2D /wr */ NO_LOOKUP_(X8664_DEC_ADD_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 2E /wr */ INVALID
  /* 2F /wr */ INVALID
  /* 30 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EB_GB_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* 31 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EV_GV_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* 32 /wr */ NO_LOOKUP_(X8664_DEC_ADD_GB_EB_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 33 /wr */ NO_LOOKUP_(X8664_DEC_ADD_GV_EV_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 34 /wr */ NO_LOOKUP_(X8664_DEC_ADD_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 35 /wr */ NO_LOOKUP_(X8664_DEC_ADD_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_LOGIC))
  /* 36 /wr */ INVALID
  /* 37 /wr */ INVALID
  /* 38 /wr */ NO_LOOKUP(X8664_DEC_CMP_EB_GB_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 39 /wr */ NO_LOOKUP(X8664_DEC_CMP_EV_GV_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 3A /wr */ NO_LOOKUP(X8664_DEC_CMP_GB_EB_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 3B /wr */ NO_LOOKUP(X8664_DEC_CMP_GV_EV_MEM, 3, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 3C /wr */ NO_LOOKUP_(X8664_DEC_CMP_AL_IB, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 3D /wr */ NO_LOOKUP_(X8664_DEC_CMP_RAX_IZ, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH))
  /* 3E /wr */ INVALID
  /* 3F /wr */ INVALID
  /* 40 /wr */ INVALID // REX:
  /* 41 /wr */ INVALID // REX:
  /* 42 /wr */ INVALID // REX:
  /* 43 /wr */ INVALID // REX:
  /* 44 /wr */ INVALID // REX:
  /* 45 /wr */ INVALID // REX:
  /* 46 /wr */ INVALID // REX:
  /* 47 /wr */ INVALID // REX:
  /* 48 /wr */ INVALID // REX:
  /* 49 /wr */ INVALID // REX:
  /* 4A /wr */ INVALID // REX:
  /* 4B /wr */ INVALID // REX:
  /* 4C /wr */ INVALID // REX:
  /* 4D /wr */ INVALID // REX:
  /* 4E /wr */ INVALID // REX:
  /* 4F /wr */ INVALID // REX:
  /* 50 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 51 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 52 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 53 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 54 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 55 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 56 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 57 /wr */ NO_LOOKUP_(X8664_DEC_PUSH_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 58 /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 59 /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5A /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5B /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5C /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5D /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5E /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 5F /wr */ NO_LOOKUP_(X8664_DEC_POP_GPR, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 60 /wr */ INVALID
  /* 61 /wr */ INVALID
  /* 62 /wr */ INVALID
  /* 63 /wr */ NO_LOOKUP_(invalid, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* 64 /wr */ INVALID
  /* 65 /wr */ INVALID
  /* 66 /wr */ INVALID
  /* 67 /wr */ INVALID
  /* 68 /wr */ NO_LOOKUP_(invalid, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 69 /wr */ NO_LOOKUP_(invalid, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_MUL))
  /* 6A /wr */ NO_LOOKUP_(invalid, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 6B /wr */ NO_LOOKUP_(invalid, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_MUL))
  /* 6C /wr */ INVALID // string
  /* 6D /wr */ INVALID // string
  /* 6E /wr */ INVALID // string
  /* 6F /wr */ INVALID // string
  /* 70 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 71 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 72 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 73 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 74 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 75 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 76 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 77 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 78 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 79 /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7A /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7B /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7C /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7D /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7E /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 7F /wr */ NO_LOOKUP_(X8664_JUMP_COND_SHORT, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 80 /wr */ NO_LOOKUP(X8664_GROUP_1_8BITS_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 81 /wr */ NO_LOOKUP(X8664_GROUP_1_ZBITS_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 82 /wr */ INVALID
  /* 83 /wr */ NO_LOOKUP_(X8664_GROUP_1_ZBITS_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 84 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EB_GB_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* 85 /wr */ NO_LOOKUP_(X8664_DEC_ADD_EV_GV_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* 86 /wr */ INVALID
  /* 87 /wr */ INVALID
  /* 88 /wr */ NO_LOOKUP(X8664_MOV_EB_GB_MEM, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 89 /wr */ NO_LOOKUP(X8664_MOV_EV_GV_MEM, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_STORE))
  /* 8A /wr */ NO_LOOKUP(X8664_MOV_GB_EB_MEM, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 8B /wr */ NO_LOOKUP(X8664_MOV_GV_EV_MEM, 2, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD))
  /* 8C /wr */ INVALID
  /* 8D /wr */ INVALID      // LEA
  /* 8E /wr */ INVALID
  /* 8F /wr */ INVALID
  /* 90 /wr */ INVALID  // handles XCHG R8w, AX
  /* 91 /wr */ INVALID
  /* 92 /wr */ INVALID
  /* 93 /wr */ INVALID
  /* 94 /wr */ INVALID
  /* 95 /wr */ INVALID
  /* 96 /wr */ INVALID
  /* 97 /wr */ INVALID
  /* 98 /wr */ INVALID
  /* 99 /wr */ INVALID
  /* 9A /wr */ INVALID
  /* 9B /wr */ INVALID
  /* 9C /wr */ INVALID
  /* 9D /wr */ INVALID
  /* 9E /wr */ INVALID
  /* 9F /wr */ INVALID
  /* A0 /wr */ INVALID
  /* A1 /wr */ INVALID
  /* A2 /wr */ INVALID
  /* A3 /wr */ INVALID
  /* A4 /wr */ INVALID
  /* A5 /wr */ INVALID
  /* A6 /wr */ INVALID
  /* A7 /wr */ INVALID
  /* A8 /wr */ INVALID
  /* A9 /wr */ INVALID
  /* AA /wr */ INVALID
  /* AB /wr */ INVALID
  /* AC /wr */ INVALID
  /* AD /wr */ INVALID
  /* AE /wr */ INVALID
  /* AF /wr */ INVALID
  /* B0 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B1 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B2 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B3 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B4 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B5 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B6 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B7 /wr */ NO_LOOKUP_(X8664_B0_TO_B7, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B8 /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* B9 /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BA /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BB /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BC /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BD /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BE /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* BF /wr */ NO_LOOKUP_(X8664_B8_TO_BF, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_MOV))
  /* C0 /wr */ NO_LOOKUP_(X8664_GROUP_1_8BITS_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* C1 /wr */ NO_LOOKUP_(X8664_GROUP_1_ZBITS_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* C2 /wr */ NO_LOOKUP_(invalid, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* C3 /wr */ NO_LOOKUP_(invalid, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* C4 /wr */ INVALID
  /* C5 /wr */ INVALID
  /* C6 /wr */ INVALID
  /* C7 /wr */ INVALID
  /* C8 /wr */ INVALID
  /* C9 /wr */ INVALID
  /* CA /wr */ INVALID
  /* CB /wr */ INVALID
  /* CC /wr */ INVALID
  /* CD /wr */ INVALID
  /* CE /wr */ INVALID
  /* CF /wr */ INVALID
  /* D0 /wr */ NO_LOOKUP_(X8664_GROUP_1_8BITS_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* D1 /wr */ NO_LOOKUP_(X8664_GROUP_1_ZBITS_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* D2 /wr */ NO_LOOKUP(X8664_GROUP_2_CL_8BITS_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* D3 /wr */ NO_LOOKUP(X8664_GROUP_2_CL_ZBITS_MEM, 4, LIST_TYPES(CPU_INSTRUCTION_TYPE_INT_ARITH, CPU_INSTRUCTION_TYPE_LOAD, CPU_INSTRUCTION_TYPE_INT_LOGIC, CPU_INSTRUCTION_TYPE_STORE))
  /* D4 /wr */ INVALID
  /* D5 /wr */ INVALID
  /* D6 /wr */ INVALID
  /* D7 /wr */ INVALID
  /* D8 /wr */ INVALID
  /* D9 /wr */ INVALID
  /* DA /wr */ INVALID
  /* DB /wr */ INVALID
  /* DC /wr */ INVALID
  /* DD /wr */ INVALID
  /* DE /wr */ INVALID
  /* DF /wr */ INVALID
  /* E0 /wr */ INVALID
  /* E1 /wr */ INVALID
  /* E2 /wr */ INVALID
  /* E3 /wr */ INVALID
  /* E4 /wr */ INVALID
  /* E5 /wr */ INVALID
  /* E6 /wr */ INVALID
  /* E7 /wr */ INVALID
  /* E8 /wr */ NO_LOOKUP_(X8664_CALL, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* E9 /wr */ NO_LOOKUP_(X8664_JUMP_UNCOND, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* EA /wr */ INVALID
  /* EB /wr */ NO_LOOKUP_(X8664_JUMP_UNCOND, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* EC /wr */ INVALID
  /* ED /wr */ INVALID
  /* EE /wr */ INVALID
  /* EF /wr */ INVALID
  /* F0 /wr */ INVALID // LOCK
  /* F1 /wr */ INVALID
  /* F2 /wr */ INVALID // REPNE/REPNZ
  /* F3 /wr */ INVALID // REP, REPE/REPZ
  /* F4 /wr */ INVALID
  /* F5 /wr */ INVALID
  /* F6 /wr */ INVALID
  /* F7 /wr */ INVALID
  /* F8 /wr */ INVALID
  /* F9 /wr */ INVALID
  /* FA /wr */ INVALID
  /* FB /wr */ INVALID
  /* FC /wr */ INVALID
  /* FD /wr */ INVALID
  /* FE /wr */ INVALID
  /* FF /wr */ INVALID

  /* 0F 00 /wr */ INVALID
  /* 0F 01 /wr */ INVALID
  /* 0F 02 /wr */ INVALID
  /* 0F 03 /wr */ INVALID
  /* 0F 04 /wr */ INVALID
  /* 0F 05 /wr */ INVALID
  /* 0F 06 /wr */ INVALID
  /* 0F 07 /wr */ INVALID
  /* 0F 08 /wr */ INVALID
  /* 0F 09 /wr */ INVALID
  /* 0F 0A /wr */ INVALID
  /* 0F 0B /wr */ INVALID
  /* 0F 0C /wr */ INVALID
  /* 0F 0D /wr */ INVALID             // 3DNow! PREFETCH on AMD, NOP on Intel
  /* 0F 0E /wr */ INVALID           // 3DNow! FEMMS
#if BX_SUPPORT_3DNOW
  /* 0F 0F /wr */ INVALID
#else
  /* 0F 0F /wr */ INVALID
#endif
  /* 0F 10 /wr */ INVALID
  /* 0F 11 /wr */ INVALID
  /* 0F 12 /wr */ INVALID
  /* 0F 13 /wr */ INVALID  // MOVLPS/PD SSE group
  /* 0F 14 /wr */ INVALID
  /* 0F 15 /wr */ INVALID
  /* 0F 16 /wr */ INVALID
  /* 0F 17 /wr */ INVALID  // MOHLPS/PD SSE group
  /* 0F 18 /wr */ INVALID    // PREFETCH HINT
  /* 0F 19 /wr */ INVALID    // multi-byte NOP
  /* 0F 1A /wr */ INVALID    // multi-byte NOP
  /* 0F 1B /wr */ INVALID    // multi-byte NOP
  /* 0F 1C /wr */ INVALID    // multi-byte NOP
  /* 0F 1D /wr */ INVALID    // multi-byte NOP
  /* 0F 1E /wr */ INVALID    // multi-byte NOP
  /* 0F 1F /wr */ INVALID    // multi-byte NOP
  /* 0F 20 /wr */ INVALID
  /* 0F 21 /wr */ INVALID
  /* 0F 22 /wr */ INVALID
  /* 0F 23 /wr */ INVALID
  /* 0F 24 /wr */ INVALID
  /* 0F 25 /wr */ INVALID
  /* 0F 26 /wr */ INVALID
  /* 0F 27 /wr */ INVALID
  /* 0F 28 /wr */ INVALID
  /* 0F 29 /wr */ INVALID
  /* 0F 2A /wr */ INVALID
  /* 0F 2B /wr */ INVALID // MOVNTPS/PD/SS/SD
  /* 0F 2C /wr */ INVALID
  /* 0F 2D /wr */ INVALID
  /* 0F 2E /wr */ INVALID
  /* 0F 2F /wr */ INVALID
  /* 0F 30 /wr */ INVALID
  /* 0F 31 /wr */ INVALID
  /* 0F 32 /wr */ INVALID
  /* 0F 33 /wr */ INVALID
  /* 0F 34 /wr */ INVALID
  /* 0F 35 /wr */ INVALID
  /* 0F 36 /wr */ INVALID
  /* 0F 37 /wr */ INVALID
#if (BX_SUPPORT_SSE >= 4) || (BX_SUPPORT_SSE >= 3 && BX_SUPPORT_SSE_EXTENSION > 0)
  /* 0F 38 /wr */ INVALID // 3-byte escape
#else
  /* 0F 38 /wr */ INVALID
#endif
  /* 0F 39 /wr */ INVALID
#if (BX_SUPPORT_SSE >= 4) || (BX_SUPPORT_SSE >= 3 && BX_SUPPORT_SSE_EXTENSION > 0)
  /* 0F 3A /wr */ INVALID // 3-byte escape
#else
  /* 0F 3A /wr */ INVALID
#endif
  /* 0F 3B /wr */ INVALID
  /* 0F 3C /wr */ INVALID
  /* 0F 3D /wr */ INVALID
  /* 0F 3E /wr */ INVALID
  /* 0F 3F /wr */ INVALID
  /* 0F 40 /wr */ INVALID
  /* 0F 41 /wr */ INVALID
  /* 0F 42 /wr */ INVALID
  /* 0F 43 /wr */ INVALID
  /* 0F 44 /wr */ INVALID
  /* 0F 45 /wr */ INVALID
  /* 0F 46 /wr */ INVALID
  /* 0F 47 /wr */ INVALID
  /* 0F 48 /wr */ INVALID
  /* 0F 49 /wr */ INVALID
  /* 0F 4A /wr */ INVALID
  /* 0F 4B /wr */ INVALID
  /* 0F 4C /wr */ INVALID
  /* 0F 4D /wr */ INVALID
  /* 0F 4E /wr */ INVALID
  /* 0F 4F /wr */ INVALID
  /* 0F 50 /wr */ INVALID
  /* 0F 51 /wr */ INVALID
  /* 0F 52 /wr */ INVALID
  /* 0F 53 /wr */ INVALID
  /* 0F 54 /wr */ INVALID
  /* 0F 55 /wr */ INVALID
  /* 0F 56 /wr */ INVALID
  /* 0F 57 /wr */ INVALID
  /* 0F 58 /wr */ INVALID
  /* 0F 59 /wr */ INVALID
  /* 0F 5A /wr */ INVALID
  /* 0F 5B /wr */ INVALID
  /* 0F 5C /wr */ INVALID
  /* 0F 5D /wr */ INVALID
  /* 0F 5E /wr */ INVALID
  /* 0F 5F /wr */ INVALID
  /* 0F 60 /wr */ INVALID
  /* 0F 61 /wr */ INVALID
  /* 0F 62 /wr */ INVALID
  /* 0F 63 /wr */ INVALID
  /* 0F 64 /wr */ INVALID
  /* 0F 65 /wr */ INVALID
  /* 0F 66 /wr */ INVALID
  /* 0F 67 /wr */ INVALID
  /* 0F 68 /wr */ INVALID
  /* 0F 69 /wr */ INVALID
  /* 0F 6A /wr */ INVALID
  /* 0F 6B /wr */ INVALID
  /* 0F 6C /wr */ INVALID
  /* 0F 6D /wr */ INVALID
  /* 0F 6E /wr */ INVALID
  /* 0F 6F /wr */ INVALID
  /* 0F 70 /wr */ INVALID
  /* 0F 71 /wr */ INVALID
  /* 0F 72 /wr */ INVALID
  /* 0F 73 /wr */ INVALID
  /* 0F 74 /wr */ INVALID
  /* 0F 75 /wr */ INVALID
  /* 0F 76 /wr */ INVALID
  /* 0F 77 /wr */ INVALID
  /* 0F 78 /wr */ INVALID
  /* 0F 79 /wr */ INVALID
  /* 0F 7A /wr */ INVALID
  /* 0F 7B /wr */ INVALID
  /* 0F 7C /wr */ INVALID
  /* 0F 7D /wr */ INVALID
  /* 0F 7E /wr */ INVALID
  /* 0F 7F /wr */ INVALID
  /* 0F 80 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 81 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 82 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 83 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 84 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 85 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 86 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 87 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 88 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 89 /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8A /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8B /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8C /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8D /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8E /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 8F /wr */ NO_LOOKUP_(X8664_JUMP_COND_LONG, 1, LIST_TYPES(CPU_INSTRUCTION_TYPE_BRANCH))
  /* 0F 90 /wr */ INVALID
  /* 0F 91 /wr */ INVALID
  /* 0F 92 /wr */ INVALID
  /* 0F 93 /wr */ INVALID
  /* 0F 94 /wr */ INVALID
  /* 0F 95 /wr */ INVALID
  /* 0F 96 /wr */ INVALID
  /* 0F 97 /wr */ INVALID
  /* 0F 98 /wr */ INVALID
  /* 0F 99 /wr */ INVALID
  /* 0F 9A /wr */ INVALID
  /* 0F 9B /wr */ INVALID
  /* 0F 9C /wr */ INVALID
  /* 0F 9D /wr */ INVALID
  /* 0F 9E /wr */ INVALID
  /* 0F 9F /wr */ INVALID
  /* 0F A0 /wr */ INVALID
  /* 0F A1 /wr */ INVALID
  /* 0F A2 /wr */ INVALID
  /* 0F A3 /wr */ INVALID
  /* 0F A4 /wr */ INVALID
  /* 0F A5 /wr */ INVALID
  /* 0F A6 /wr */ INVALID
  /* 0F A7 /wr */ INVALID
  /* 0F A8 /wr */ INVALID
  /* 0F A9 /wr */ INVALID
  /* 0F AA /wr */ INVALID
  /* 0F AB /wr */ INVALID
  /* 0F AC /wr */ INVALID
  /* 0F AD /wr */ INVALID
  /* 0F AE /wr */ INVALID
  /* 0F AF /wr */ INVALID
  /* 0F B0 /wr */ INVALID
  /* 0F B1 /wr */ INVALID
  /* 0F B2 /wr */ INVALID // LSS
  /* 0F B3 /wr */ INVALID
  /* 0F B4 /wr */ INVALID // LFS
  /* 0F B5 /wr */ INVALID // LGS
  /* 0F B6 /wr */ INVALID
  /* 0F B7 /wr */ INVALID // MOVZX_GwEw
  /* 0F B8 /wr */ INVALID
  /* 0F B9 /wr */ INVALID
  /* 0F BA /wr */ INVALID
  /* 0F BB /wr */ INVALID
  /* 0F BC /wr */ INVALID
  /* 0F BD /wr */ INVALID
  /* 0F BE /wr */ INVALID
  /* 0F BF /wr */ INVALID // MOVSX_GwEw
  /* 0F C0 /wr */ INVALID
  /* 0F C1 /wr */ INVALID
  /* 0F C2 /wr */ INVALID
  /* 0F C3 /wr */ INVALID // MOVNTI SSE group
  /* 0F C4 /wr */ INVALID
  /* 0F C5 /wr */ INVALID
  /* 0F C6 /wr */ INVALID
  /* 0F C7 /wr */ INVALID // CMPXCHG8B G9 group
  /* 0F C8 /wr */ INVALID
  /* 0F C9 /wr */ INVALID
  /* 0F CA /wr */ INVALID
  /* 0F CB /wr */ INVALID
  /* 0F CC /wr */ INVALID
  /* 0F CD /wr */ INVALID
  /* 0F CE /wr */ INVALID
  /* 0F CF /wr */ INVALID
  /* 0F D0 /wr */ INVALID
  /* 0F D1 /wr */ INVALID
  /* 0F D2 /wr */ INVALID
  /* 0F D3 /wr */ INVALID
  /* 0F D4 /wr */ INVALID
  /* 0F D5 /wr */ INVALID
  /* 0F D6 /wr */ INVALID
  /* 0F D7 /wr */ INVALID
  /* 0F D8 /wr */ INVALID
  /* 0F D9 /wr */ INVALID
  /* 0F DA /wr */ INVALID
  /* 0F DB /wr */ INVALID
  /* 0F DC /wr */ INVALID
  /* 0F DD /wr */ INVALID
  /* 0F DE /wr */ INVALID
  /* 0F DF /wr */ INVALID
  /* 0F E0 /wr */ INVALID
  /* 0F E1 /wr */ INVALID
  /* 0F E2 /wr */ INVALID
  /* 0F E3 /wr */ INVALID
  /* 0F E4 /wr */ INVALID
  /* 0F E5 /wr */ INVALID
  /* 0F E6 /wr */ INVALID
  /* 0F E7 /wr */ INVALID // MOVNTQ/MOVNTDQ SSE group
  /* 0F E8 /wr */ INVALID
  /* 0F E9 /wr */ INVALID
  /* 0F EA /wr */ INVALID
  /* 0F EB /wr */ INVALID
  /* 0F EC /wr */ INVALID
  /* 0F ED /wr */ INVALID
  /* 0F EE /wr */ INVALID
  /* 0F EF /wr */ INVALID
  /* 0F F0 /wr */ INVALID // LDDQU SSE group
  /* 0F F1 /wr */ INVALID
  /* 0F F2 /wr */ INVALID
  /* 0F F3 /wr */ INVALID
  /* 0F F4 /wr */ INVALID
  /* 0F F5 /wr */ INVALID
  /* 0F F6 /wr */ INVALID
  /* 0F F7 /wr */ INVALID
  /* 0F F8 /wr */ INVALID
  /* 0F F9 /wr */ INVALID
  /* 0F FA /wr */ INVALID
  /* 0F FB /wr */ INVALID
  /* 0F FC /wr */ INVALID
  /* 0F FD /wr */ INVALID
  /* 0F FE /wr */ INVALID
  /* 0F FF /wr */ INVALID
