#define X8664_JUMP_COND_SHORT_HEAD \
	CPU_X8664_CONDITIONAL_FLAG_MAKEDEP(CPU_X8664_DEC_FIRST_OPCODE & 0x0F, 0)
	
#define X8664_JUMP_COND_SHORT_16BITS

#define X8664_JUMP_COND_SHORT_32BITS

#define X8664_JUMP_COND_SHORT_64BITS

#define X8664_JUMP_COND_SHORT_TAIL \
	SET_RESULT_TYPE_BRANCH_AUTOMATIC(CPU_DECODER_GET_NEXT_INSTRUCTION_ADDR+(Bit32s)this->state->bochs_inst.Id(), CPU_BRANCH_TYPE_CONDITIONAL)

/******************************************************************/

#define X8664_JUMP_COND_LONG_HEAD \
	CPU_X8664_CONDITIONAL_FLAG_MAKEDEP(CPU_X8664_DEC_SECOND_OPCODE & 0x0F, 0)
	
#define X8664_JUMP_COND_LONG_16BITS

#define X8664_JUMP_COND_LONG_32BITS

#define X8664_JUMP_COND_LONG_64BITS

#define X8664_JUMP_COND_LONG_TAIL \
	SET_RESULT_TYPE_BRANCH_AUTOMATIC(CPU_DECODER_GET_NEXT_INSTRUCTION_ADDR+(Bit32s)this->state->bochs_inst.Id(), CPU_BRANCH_TYPE_CONDITIONAL)

/******************************************************************/
#define X8664_JUMP_UNCOND_HEAD

#define X8664_JUMP_UNCOND_16BITS

#define X8664_JUMP_UNCOND_32BITS

#define X8664_JUMP_UNCOND_64BITS

#define X8664_JUMP_UNCOND_TAIL \
	SET_RESULT_TYPE_BRANCH_AUTOMATIC(CPU_DECODER_GET_NEXT_INSTRUCTION_ADDR+(Bit32s)this->state->bochs_inst.Id(), CPU_BRANCH_TYPE_UNCONDITIONAL)

/******************************************************************/
#define X8664_CALL_HEAD

#define X8664_CALL_16BITS

#define X8664_CALL_32BITS

#define X8664_CALL_64BITS

#define X8664_CALL_TAIL \
	SET_RESULT_TYPE_BRANCH_AUTOMATIC(CPU_DECODER_GET_NEXT_INSTRUCTION_ADDR+(Bit32s)this->state->bochs_inst.Id(), CPU_BRANCH_TYPE_UNCONDITIONAL)

/******************************************************************/

